### ISSUE TITLE
Download videos in low resolution instead of ffmpeg transcode

### ISSUE THREAD

**Issue by outusuke** [openzim/youtube#114]
Is it possible to download in low resolution instead of --low-quality?
 Because it takes a long time to convert and consume many resources on a common PC

**Comment by outusuke** [comment]
I realized that using the webm takes an average of 20 minutes for each video and the mp4 for about 3 minutes

**Comment by rgaudin** [comment]
No, not easily because videos each have different available formats and resolution and we want something we can rely on.
So we request `best` resolution and convert-down from there.

If we were to request a particular format, it would fail on many videos because it might not be present.

We could request `worst` but it's not consistent either and many are available as `3gp` which is terrible (worst than our low-quality which is already very aggressive).

I doubt there's a single setting that works best than current. We could allow people to customize the youtube-dl format request but I'm not sure how much demand there is for that.

**Comment by kelson42** [comment]
Probably we should close this ticket as not fixeable (or already implemented properly).
