### ISSUE TITLE
How come the default background color always seems to be a shade of pink?

### ISSUE THREAD

**Issue by Popolechien** [openzim/youtube#115]
The recipe on zimfarm when creating playlist says that if no color is specified background will default to main color of profile image, but more often than not I simply have a shade of pink :-/
Why not a white background as default?
![Capture d’écran 2020-08-13 à 14 06 18](https://user-images.githubusercontent.com/21675885/90134696-d999ce00-dd71-11ea-87bd-fa7f32ddad65.png)

**Comment by rgaudin** [comment]
As for the light-pink, this clearly matches the profile picture (skin color).

I don't know why we use those auto-color as background ; probably because it looks dull in plain white. You can override this in the recipe of course.

Should we change the default? I have no opinion.

**Comment by kelson42** [comment]
@Popolechien I belive current default behaviour is proper. Why you don't set white in te recipe? Sounds easy.

**Comment by Popolechien** [comment]
I guess I don't set white because I always forget about it. Also just realized that the profile image is in fact the zim icon (as opposite to the page banner), which in the case at hand has a lot of pink in it indeed.

I nevertheless find this quite adventurous as the page layout rarely ever integrates well with an averaged out logo color. I would definitely think that plain dull white as default is the safer option.

**Comment by kelson42** [comment]
@Popolechien So you saiy that a similar color beetween background and banner is a worse combination than any logo with withe background?

**Comment by Popolechien** [comment]
@kelson42 I'm saying that currently the default color choice is more or less guesswork and that more often than not it ends up being a miss. I'd rather have 100% reliable, dull white than 10% on-target, aligned branded colors. 

To take another example, for TED we're lucky it picked white, but there was a chance it could have picked bright red as background color. Not sure it's would have been the best user experience, and unless we have some sort of systematic human QA I do not think it would be wise to hope for the best for every new playlist we create.

**Comment by kelson42** [comment]
@Popolechien So "shade of pink" is a "miss" because?

**Comment by Popolechien** [comment]
I don't see the problem with having some sort of continuity across zim files - quite the opposite (I don't remember where the requirement was made, but whatever).
If we want to scale and cannot affort human QA, then we need to find a solution that removes the need for such tedious QA.

In the case at hand pink is not on-brand, it's frankly ugly, doesn't match the overall layout and I'm yet to find a UX guide that says "random unassorted colors are best".

To be clear I do not push for white background as much as transparent - meaning white in normal mode but black in dark mode.

**Comment by rgaudin** [comment]
Handling dark mode is different than just setting `background-color: transparent` (that defaults to white usually).

Dark mode triggers an alternative set of CSS rules so handling dark mode means preparing color sets (or other adjustments) for both mode. I'm all for it if someone (Christina?) wants to propose something.

As for setting a fixed background instead of auto-mode, I'd advise we choose something else than white which looks a lot worst than the light pink on the above example (personal taste).

**Comment by Popolechien** [comment]
@siemsie Thoughts?

**Comment by kelson42** [comment]
@Popolechien I don't think we can do really much on this ticket. You find shade of pink ugly, OK. This is something absolutly subjective and I'm not comfortable to work on this base, in particular if there is no consensus on this. To the contrary, the current situation is the fruit of a discussion with many factual and measearables things. If you believe we should have ZIM which should be more similar even with different contents, then you should quicly open a ticket because we always try to do the opposite as much as possible.

**Comment by rgaudin** [comment]
OK, question answered then. We can open a ticket to request a change if desired.
