### ISSUE TITLE
Use newer multithreaded youtube downloader from scraperlib

### ISSUE THREAD

**Issue by satyamtg** [openzim/youtube#118]
We now have support for downloadeing youtube videos on a fixed number of threads in scraperlib. Hence, we shall use that instead of the current approach of downloading in batches

**Comment by rgaudin** [comment]
We definitely should but we shall keep an alternative method for S3 download/upload (IO bound) and ffmpeg (cpu bound)

**Comment by kelson42** [comment]
@benoit74 Still a valid issue? Or maybe already foxed in `2.3.0`?

**Comment by benoit74** [comment]
If I get it correctly, this is still not implemented:
- goal of this issue is to use https://github.com/openzim/python-scraperlib/blob/7d498319baadba715316c15cf9857ff2f6974a00/src/zimscraperlib/download.py#L18C7-L18C24
- currently downloads are still not done with it: https://github.com/openzim/youtube/blob/main/scraper/src/youtube2zim/scraper.py#L739-L740

**Comment by benoit74** [comment]
Let's focus on new UI for 3.0

**Comment by benoit74** [comment]
Unfortunately, youtube downloader from scraperlib does not permit concurrent downloads from s3 cache, so it is way more complex to implement than needed.

Closing this issue for now, we have to way for scraperlib to properly support downloads from s3 as well
