### ISSUE TITLE
Unable to connect to Youtube API v3

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#133]
https://farm.openzim.org/pipeline/5fb757db5e7b6ccea3dd1b48/debug

**Comment by rgaudin** [comment]
Might well be what I was talking about on the call the other day: suspension of key for inactivity

**Comment by kelson42** [comment]
If this is confirmed, would the run of many recipes every quarter (instead of every semester) help?

**Comment by rgaudin** [comment]
If it is, yes

**Comment by kelson42** [comment]
@rgaudin Should we close this ticket?

**Comment by rgaudin** [comment]
Apparently the whole project (keys are attached to a project which itself holds the quota) was suspended but I couldn't see any indication of such suspension on the Google console.
Had to create new projects instead. Because of the limited number of projects an account can hold and the fact that deletion is not immediate (you can revert it for 30 days), I've created them on a new account (`reg+zimfarm@kiwix.org`) and deleted the projects from previous account.
Recreated all projects, and keys, with the current list of IPs we want to whitelist.

Updated all recipes to quarterly.
