### ISSUE TITLE
Update the ReadMe.md file

### ISSUE THREAD

**Issue by jo780-full** [openzim/youtube#189]
The installation process is missing a crucial step, causing issues with the get_js_deps.sh file not being downloaded during the installation of youtube2zim using pip3. To address this, I suggest updating the installation section in the readme with the following steps:
**FIX**
1. clone the repository
`git clone https://github.com/openzim/youtube`
`cd youtube`

2. Run the get_js_deps.sh script:
`./get_js_deps.sh`

3.Copy assets to the virtual environment:
`cp -Rf /path_to_your_directory/youtube/src/youtube2zim/templates/assets /path_to_your_env/lib/python3.10/site-packages/youtube2zim/templates/
`

This should fix the no videojs-ogvjs.js  error .

**Comment by jo780-full** [comment]
Hey @benoit74 ,
I don't think the `get_js_deps.sh` is being run upon installation the assets aren't present in the virtual environment when i run pip install youtube2zim in my virtual environment (.venv) all the required assets aren't present in `.venv/lib/python3.10/site-packages/youtube2zim/templates/assets/ ` . That's what is causing the issue.

**Comment by jo780-full** [comment]
how can we get it to run during installation ?

a simple workaround is to download the script
build the dependencies by running the script and then copying them into the package directory within the virtual environment

but i don't think it's very user-friendly as it involves a lot of manual steps to set up.

**Comment by benoit74** [comment]
Hi, thank you for reporting that.

Now that I'm in front of my laptop and the whole codebase, I realize that the problem is in fact "simply" that we did not updated the documentation after the migration to `hatch` instead of `setuptools`.

Please read the new README.md and tell me if it is still not clear. 

Sorry for the time you lost adjusting the README for this lack of update.
