### ISSUE TITLE
Set autoplay option to always be true for videos in new UI

### ISSUE THREAD

**Issue by dan-niles** [openzim/youtube#233]
With the implementation of #229, the video.js player has been configured to have autoplay set to false by default. The entrypoint.py script includes an argument called `--autoplay`, which allows the user to enable or disable autoplay functionality.

We need to update the scraper so that it can convey this autoplay configuration to the Vue.js UI.

**Comment by Kaif9999** [comment]
Hey I wanted to contribute to this issue is it still open.

**Comment by kelson42** [comment]
@Kaif9999 Hi, it's open but assigned to @dan-niles, maybe you can find one which is not assigned?

**Comment by Kaif9999** [comment]
Hi, also wanted to ask are there any issues I can work with I am a beginner to open source with the knowledge of Python have built a few small projects in it, I am also proficient in html, css, javascript

**Comment by benoit74** [comment]
@Kaif9999 youtube scraper is indeed undergoing a significant effort of rewriting, so this issue is assigned to Dan because he is the best one to tackle this issue.

Please also prefer to consider issues tagged "good first issue" and not assigned to someone (or without activity by this person for months) preferably. Preferably because it is ok to ask for contributing on issues not matching these criteria, but the chances we say "no" are higher obviously ^^

More information on how to contribute at www.kiwix.org/code

**Comment by dan-niles** [comment]
In #237 we decided to remove the `--autoplay` argument and set `autoplay: true` always.
