### ISSUE TITLE
Failing cypress test on `main` branch

### ISSUE THREAD

**Issue by benoit74** [openzim/youtube#245]
See https://github.com/openzim/youtube/actions/runs/9664367435/job/26659888824

What is weird is that test was OK on the PR.

I tried to re-run the workflow to check if test was just flaky but result is same.

@dan-niles could you please have a look (nothing urgent).

**Comment by dan-niles** [comment]
The issue is in the following lines of code:
https://github.com/openzim/youtube/blob/d56c272fce4d7504985cf63116f8a58fd98ced19/zimui/src/components/video/VideoPlayer.vue#L36-L50

When the cypress test executes the line mentioned below, the code above gets called. Since we are not mocking the video files, videojs cannot load a video, hence an error is thrown whenever `player.value.play()` is called.
https://github.com/openzim/youtube/blob/d56c272fce4d7504985cf63116f8a58fd98ced19/zimui/cypress/e2e/video_player_page.cy.ts#L50

Intercepting the video loaded by Video.js and replacing it with a mock video should fix this issue.
