### ISSUE TITLE
Write integration tests for the scraper

### ISSUE THREAD

**Issue by dan-niles** [openzim/youtube#253]
It would be beneficial if we could write integration tests for the YouTube scraper similar to the one in [zimit](https://github.com/openzim/zimit/blob/main/tests-integration/integration.py).

**Comment by benoit74** [comment]
> Do you have any suggestions for any other integration tests that might be useful?

I would suggest to test for subtitles (there is only one in openZIM test channel, but still good to check it is still there). 

Nothing else to suggest, I think this will be a good start and it is always easier to add tests to an existing suite when we discover a bug rather than having to start from scratch. From my PoV job's is sufficient since this goal is reached.
