### ISSUE TITLE
UI is not always really relevant when many playlists are in the ZIM

### ISSUE THREAD

**Issue by benoit74** [openzim/youtube#337]
We have two tabs in Youtube UI front page:
- Videos
- Playlists

By default, the videos tab is selected

The videos tab show videos from the default playlist (first one of the list, first one of the channel, ...)

This means that by default when many playlists are present, we see only a subset of all videos. This is not really relevant / confusing.

See e.g. https://library.kiwix.org/viewer#s2underground_en_all . In this ZIM, at first sight, one can believe there is only 35 videos in the ZIM, because by default the "Long-Form Content" playlist has been selected.

I see multiple solutions forward:
- (1) drop the distinction between videos and playlists ; when there is only one playlist or no playlist at all, display the videos inside the playlist ; otherwise, display the list of playlists (maybe with a design where we see thumbnails from first videos of every playlist, like below - taken from Youtube)

![image](https://github.com/user-attachments/assets/24edde30-8ce0-4677-84dd-4d2b3fbfdc4f)

- (2) by default, when there is multiple playlists, remove the "Videos" tab from UI and only show the "Playlists" one.

While 2 is obviously way easier to implement, I believe that only something like 1 make real sense.

**Comment by dan-niles** [comment]
I like the first approach. This was what I originally wanted to do with the "Home" tab in my proposed [Figma design](https://www.figma.com/design/f922aAI4PJry9ioHWm4Zd4/Kiwix-Youtube-UI-Revamp?node-id=0-1&t=drxPrJNx7m7JY1Tg-1). We can use this layout when there are multiple playlists in the ZIM in the "Videos" tab.

I propose we make the UI something like this:
![home](https://github.com/user-attachments/assets/7af8bcdf-bd2d-4ba9-a16b-aae22339bed1)

Each playlist in the ZIM will be displayed in a row. We can display about 12 videos in each row in a carousel and give a link to "View More" which would lead to the respective playlist page.

We might need to a add a new key to `channel.json` called `playlists` to store a list of playlists along with 12 [VideoPreview](https://github.com/openzim/youtube/blob/0b9bed587f5a2cb890d272aee848b89cb2fb5fe8/scraper/src/youtube2zim/schemas.py#L50) objects each so that we won't have to load all the playlist videos to render this page.

WDYT?

**Comment by benoit74** [comment]
@Popolechien @kelson42 do you have any views to share on this important change or shall we proceed?

**Comment by Popolechien** [comment]
LGTM, you are right that displaying a jumble of videos from the get-go is not ideal.

**Comment by benoit74** [comment]
OK, so I consider this means we have a "go" to implement this change. 

Thank you @dan-niles for the precise proposal / UI mock; shall I assign you the issue because you intend to develop this (no pressure)?

**Comment by dan-niles** [comment]
@benoit74 Sure, I'd like to work on this.
