### ISSUE TITLE
What happens when there is no video in channel / playlist?

### ISSUE THREAD

**Issue by benoit74** [openzim/youtube#347]
From https://github.com/openzim/youtube/pull/341#pullrequestreview-2324996456

What happens when the channel has no video, or the playlist(s) have no video in the end? Do we create an almost empty ZIM?

We need to ensure that scraper fails in such a situation with a clear error message.

**Comment by dan-niles** [comment]
Since #341 ensures that all empty playlists are ignored, it's better to throw an error if no playlists with videos remain, rather than creating an empty ZIM file.

In the [extract_videos_list](https://github.com/openzim/youtube/blob/f9d4b1ebfcee5eb7e232d52e8d1eef004a406ac7/scraper/src/youtube2zim/scraper.py#L594-L621) method, after removing the empty playlists, adding the following two lines should be enough to throw an error:

```python3
for playlist in empty_playlists:
    self.playlists.remove(playlist)

# Add these two lines
if not self.playlists:
    raise Exception("No videos found in playlists")
```

WDYT?

**Comment by benoit74** [comment]
I like it!
