### ISSUE TITLE
Unable to create BIL tunisia ZIM file

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#58]
Here is the failing task:
https://farm.openzim.org/pipeline/5df2575f9700f5b918363377

and the error log:
```
{"log":"Attempting to update youtube-dl…\n","stream":"stdout","time":"2019-12-12T15:09:02.973233503Z"}
{"log":"Collecting youtube-dl\n","stream":"stdout","time":"2019-12-12T15:09:06.053961104Z"}
{"log":"  Downloading https://files.pythonhosted.org/packages/58/38/1215e2bae8cd0b1a52621740add46cebfa8bb988a48cd61cf7cccf7c09c6/youtube_dl-2019.11.28-py2.py3-none-any.whl (1.8MB)\n","stream":"stdout","time":"2019-12-12T15:09:07.231059202Z"}
{"log":"Installing collected packages: youtube-dl\n","stream":"stdout","time":"2019-12-12T15:09:07.822766635Z"}
{"log":"  Found existing installation: youtube-dl 2019.11.22\n","stream":"stdout","time":"2019-12-12T15:09:07.822815384Z"}
{"log":"    Uninstalling youtube-dl-2019.11.22:\n","stream":"stdout","time":"2019-12-12T15:09:07.826631323Z"}
{"log":"      Successfully uninstalled youtube-dl-2019.11.22\n","stream":"stdout","time":"2019-12-12T15:09:08.095820785Z"}
{"log":"Successfully installed youtube-dl-2019.11.28\n","stream":"stdout","time":"2019-12-12T15:09:10.112719502Z"}
{"log":"ERROR:FAILED. An error occured: unsupported locale setting\n","stream":"stderr","time":"2019-12-12T15:09:11.971962701Z"}
```

**Comment by rgaudin** [comment]
There's no direct matching between ISO639-3 code `ara` (Arabic, general) and an Arabic locale. In this case, we'd want the Tunisian Arabic, `ar_TN`. We could specify `aeb` which is the ISO639-3 code for Tunisian Arabic but we have no library to give us `ar_TN` from those anyway.

Locale being used for localizations of some strings (only available in English and French ATM) and dates, it's not much of a problem.

Fixed by:
- being permissive on non-matching locale for ISO language. defaulting to English. With an error message at the begining of the process.
- Allowing specifying `--locale` to bypass this or just to set a different locale than the content language.
- Setting `--locale fr_FR` on bil-tunisia so it uses the french translations instead of english as it's more suitable.

**Comment by kelson42** [comment]
@rgaudin Looks like we have somewhere a bug upstream in a Pythonlibrary?

**Comment by rgaudin** [comment]
I don't think so. We have no ISO-to-locale library. We are using a library to convert from 639-3 to 639-1 and this works fine.

It's just that we were using the 639-1 to set the locale because the parser is kind enough to accept it for the big languages but it's not its job to convert from ISO language codes.

There might be a library somewhere that does this but a (very) quick search didn't help.
