### ISSUE TITLE
Verify new encoding of video/audio

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#74]
New ZIM files seems to be around 30% bigger than before and we don't understand why.

**Comment by rgaudin** [comment]
To be more specific, we have:

* http://tmp.kiwix.org/ubongo_fr_all_2020-03.zim **1.1GB** created on March 13th. This one is known to **not have audio**.
* http://download.kiwix.org/zim/other/ubongo_fr_all_2020-03.zim **1.8GB** created on March 15th. This one **has audio**.

Because of the audio issue, we now have a slightly different process than before:

* We used to recompress (this recipe is `--low-quality`) from the _webm video+audio_ file served by Google. We don't know what quality this was.
* Now, we recompress from _best webm audio_ merged with _best webm video_

This change might have had a big impact on the output files size. But also, one video had been added on March 14th so the second file has one more video.

We should:

1. Compare the individual file sizes of videos inside the two different ZIM to decide whether the difference can be explained by audio only.
1. If not, we should look into maybe refining the recompress arguments for ffmpeg: https://github.com/openzim/youtube/blob/fc174b681c6d907641b8975d3e73b983cf4bf7e9/youtube2zim/converter.py#L70

``` py
    video_codecs = {"mp4": "h264", "webm": "libvpx"}
    audio_codecs = {"mp4": "aac", "webm": "libvorbis"}
    params = {"mp4": ["-movflags", "+faststart"], "webm": []}

    args = ["ffmpeg", "-y", "-i", f"file:{src_path}"]

    if low_quality:
        args += [
            "-codec:v",
            video_codecs[video_format],
            "-quality",
            "best",
            "-cpu-used",
            "0",
            "-b:v",
            "300k",
            "-qmin",
            "30",
            "-qmax",
            "42",
            "-maxrate",
            "300k",
            "-bufsize",
            "1000k",
            "-threads",
            "8",
            "-vf",
            "scale='480:trunc(ow/a/2)*2'",
            "-codec:a",
            audio_codecs[video_format],
            "-b:a",
            "128k",
        ]
    else:
        args += [
            "-codec:v",
            video_codecs[video_format],
            "-quality",
            "best",
            "-cpu-used",
            "0",
            "-bufsize",
            "1000k",
            "-threads",
            "8",
            "-codec:a",
            audio_codecs[video_format],
        ]
    args += params[video_format]
    args += [f"file:{tmp_path}"]
```

**Comment by rgaudin** [comment]
Video encoding seems identical. Comparing the file sizes of skin-of-color between Feb (without audio) and March (2.1.3), it seems that most of the difference is due to the lacking audio track (given we request it to be 128kb/s).

Video | March Size | Feb Size | Growth | Duration | Expected Diff
------------ | ------------- | ------------- | ------------- | ------------- | -------------
59qY49xdrpA.webm | 64.78 MiB | 33.84 MiB | 30.94 MiB 191% | 30:32 | 27.95 MiB
J_p9lr-pbW4.webm | 50.86 MiB | 25.25 MiB | 25.61 MiB 201% | 24:42 | 22.61 MiB
L_tFXQmr4f4.webm | 62.78 MiB | 31.06 MiB | 31.72 MiB 202% | 31:24 | 28.75 MiB
VZc2PBBfQUo.webm | 10.73 MiB | 5MiB | 5.73 MiB 214% | 5:28 | 5 MiB
YMe_9NlooeI.webm | 50.51 MiB | 25.38 MiB | 25.13 MiB 198% | 24:09 | 22.11 MiB
lDgUCN4IuY0.webm | 30.13 MiB | 19.06 MiB | 11.08 MiB 158% | 10:31 | 9.63 MiB

It's still a few MB larger than it should, accounting audio.

Although we set the audio bitrate to `128kb/s`, it seems that setting the sample rate to `44KHz` does reduces the file size to approx. the amount we're looking for so I'd advise we add `-ar 44100`.

Skin of color wasn't run before the audio bug so I am re-running mali for which we have a december ZIM (123 MiB).

**Comment by rgaudin** [comment]
New Mali ZIM is `126 MiB` so a slight 3MiB increase. Will commit the 44Khz and close.
