### ISSUE TITLE
Unnecessary duplicate of first video on top of playlist

### ISSUE THREAD

**Issue by Popolechien** [openzim/youtube#85]
The first video on the playlist is duplicated and shown on top (both on android and win10)

![image](https://user-images.githubusercontent.com/21675885/80113309-6f6eda80-8582-11ea-9a79-f49cf5e62a41.png)

The issue seems to be fairly old, as I see the same issue in [a zim from June 2018](
http://library.kiwix.org/crashcourse_en_all_2018-06/A/index.html) and [2019 ](http://library.kiwix.org/les-fondamentaux_fr_all_2019-12/A/home.html#1 ) but not in [July 2018](http://library.kiwix.org/ted_en_business_2018-07/A/index.html)

**Comment by rgaudin** [comment]
It's on purpose. That's been the behavior since forever. I mentioned it when we wrote 2.0.
This video in home page is just a preview.

Reclassifying as enhancement. We should hear @kelson42 and @dattaz before changing this.

**Comment by kelson42** [comment]
I'm in favour of the suppression of the duplicate as well.

**Comment by dattaz** [comment]
I don't remember how this video is chosen, but the idea was to has the same behavior as you browse on youtube, for exemple https://www.youtube.com/user/crashcourse you have a "preview" video.

**Comment by rgaudin** [comment]
It's not chosen, it's just the first video from the playlist.

On youtube, there's one welcome video per-channel. I suppose we replicated the graphical feeling but we don't choose the video because we can't: the welcome video only make sense if you're building a channel and would be independant to the playlist so it would require some UI redo.

I think what we can do at the moment is keep using the first one to get that nice preview UI but remove that video from the list that follows.

**Comment by satyamtg** [comment]
@kelson42 @Popolechien I agree with @rgaudin that we remove the first video from the video list for now. Have done this and also added a "Read more" to link to the page of the first video in the list. See #86
